server:
  port: 8095

springdoc:
  swagger-ui:
    path: "/swagger"
    disable-swagger-default-url: true
    use-root-path: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tarifficator-db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    default-schema: "${app.schema}"
    change-log: db/changelog/changelog-master.xml

preliquibase:
  enabled: true

integration:
  service:
    product:
      method:
        update-tariff: /product/update-tariff
      base-url: http://localhost:8195


app:
  schema: "tariff_service"
