server:
  port: 8195

springdoc:
  swagger-ui:
    path: "/swagger"
    disable-swagger-default-url: true
    use-root-path: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tarifficator-db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
      default_schema: "${app.schema}"
  liquibase:
    default-schema: "${app.schema}"
    change-log: db/changelog/changelog-master.xml
preliquibase:
  enabled: true

app:
  schema: "product_service"

integration:
  service:
    tariff:
      base-url: http://localhost:8095
      method:
        delete-tariff: /tariff/delete/{tariffId}
        save-tariff: /tariff/integration/save
    auth:
      base-url: http://localhost:8080
      method:
        valid: /auth/verify