services:

  profile-service:
    build: .
    container_name: "profile-service"
    image: "profile-service"
    depends_on:
      - db-service
    networks:
      - backend-tarifficator
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - 8085:8085